lab:
  profile: E:/opengms-lab/uploadPath
  # 资源存放路径
  repository:
    workspace: E:/opengms-lab/workspace

#日志配置
logging:
  config: classpath:log4j2-config-dev.xml
  file:
    path: E:/opengms-lab/log