lab:
  profile: E:/opengms-lab/admin/uploadPath

#日志配置
logging:
  config: classpath:log4j2-config.xml
  file:
    path: E:/opengms-lab/admin/log

spring:
  rabbitmq:
    host: 172.21.212.177 # rabbitMQ的ip地址
    port: 8071 # 端口
    #    addresses: 172.21.212.177:8071, 172.21.212.177:8072, 172.21.212.177:8073
    username: ogms
    password: ogms
    virtual-host: /   # 虚拟主机
    listener:
      simple:
        prefetch: 1 # 每次从MQ中取出一条消息进行消费
        acknowledge-mode: auto  # 自动确认
        retry:
          enabled: true # 开启重试机制
          initial-interval: 1000 # 重试间隔时间
          multiplier: 3 # 重试倍数
          max-attempts: 4 # 最大重试次数